[
  {
    student_id: 1,
    course_id: 1,
    status: 'enrolled',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    student_id: 1,
    course_id: 2,
    status: 'enrolled',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    student_id: 1,
    course_id: 5,
    status: 'cancelled',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    student_id: 2,
    course_id: 7,
    status: 'enrolled',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    student_id: 2,
    course_id: 8,
    status: 'enrolled',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    student_id: 2,
    course_id: 3,
    status: 'cancelled',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    student_id: 3,
    course_id: 3,
    status: 'enrolled',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    student_id: 4,
    course_id: 4,
    status: 'enrolled',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    student_id: 4,
    course_id: 5,
    status: 'enrolled',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    student_id: 5,
    course_id: 3,
    status: 'enrolled',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    student_id: 5,
    course_id: 4,
    status: 'enrolled',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
